name: 'GitHub Pages URL shortener'
description: 'Use GitHub Pages as your URL shortener'
inputs:
  path:
    description: 'Path to the website root'
    required: false
    default: '.'
  json:
    description: 'Path to the JSON config file'
    required: false
    default: 'links.json'
  template:
    description: 'Path to the template file'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'